<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxxvMj3\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxxvMj3/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQxxvMj3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQxxvMj3\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerQxxvMj3\srcApp_KernelProdContainer([
    'container.build_hash' => 'QxxvMj3',
    'container.build_id' => '94e3378b',
    'container.build_time' => 1583409370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxxvMj3');
