<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUspMavt\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUspMavt/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUspMavt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUspMavt\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerUspMavt\srcApp_KernelProdContainer([
    'container.build_hash' => 'UspMavt',
    'container.build_id' => '84e8bb5d',
    'container.build_time' => 1583722356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUspMavt');
