<?php declare(strict_types=1);
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Thứ năm, 05 Tháng ba năm 2020 18:48:47 +07.

define('DOMJUDGE_VERSION', '7.2.0');

define('BINDIR',      '/home/chinhhi/domjudge/domserver/bin');
define('ETCDIR',      '/home/chinhhi/domjudge/domserver/etc');
define('WEBAPPDIR',   '/home/chinhhi/domjudge/domserver/webapp');
define('LIBDIR',      '/home/chinhhi/domjudge/domserver/lib');
define('SQLDIR',      '/home/chinhhi/domjudge/domserver/sql');
define('LIBVENDORDIR','/home/chinhhi/domjudge/domserver/lib/vendor');
define('LOGDIR',      '/home/chinhhi/domjudge/domserver/log');
define('RUNDIR',      '/home/chinhhi/domjudge/domserver/run');
define('TMPDIR',      '/home/chinhhi/domjudge/domserver/tmp');
define('SUBMITDIR',   '/home/chinhhi/domjudge/domserver/submissions');

define('BASEURL',     'http://tdmu-judge.vn');

define('SUBMITCLIENT_ENABLED', 'yes');
